order:
  name: order
  postgres:
    appUsername: otususer
    appPassword: otususer
    appDatabase: otusdb
    appDbUrl: jdbc:postgresql://postgres-service:5432/order_db
  service:
    port: &orderServicePort 8080
    type: ClusterIP
  ingress:
    enabled: true
    tls: false
    rules:
    - host: arch.homework
      http:
        paths:
        - path: /aboldyrev/order($|/)(.*)
          service:
            port: *orderServicePort
hosts:
  authurl: 'http://auth-service:8080/auth'
  accounturl: 'http://account-service:8080/pay'
