apiVersion: v1
kind: Service
metadata:
  name: {{ include "order.fullname" . }}-service
spec:
  selector:
    app: {{ include "order.fullname" . }}
  ports:
    - protocol: TCP
      name: web
      port: {{.Values.order.service.port}}
      targetPort: {{.Values.order.service.port}} 
  type: {{.Values.order.service.type}} 
